version: "3"

services:
  catalog_db_postgres:
    image: "postgres:14.0"
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: catalog_db
      POSTGRES_PASSWORD: Condien123@
      POSTGRES_DB: catalog_service
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  order_db_postgres:
    image: "postgres:14.0"
    ports:
      - "5434:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: order_db
      POSTGRES_PASSWORD: Condien1234@
      POSTGRES_DB: order_service
    volumes:
      - ./db-data/order-postgres/:/var/lib/postgresql/data
